### ISSUE TITLE
instagr.rbで画像が表示できない

### ISSUE THREAD

**Issue by kp1** [tdiary/tdiary-contrib#102]
size:medium以下の画像が表示されていないようです。

Failed Open URL.. http://instagr.am/p/KCVHPgNKtN/
757: unexpected token at 'The maxwidth parameter must be greater than 320'

**Comment by satoryu** [comment]
Use [instagram.rb](https://github.com/tdiary/tdiary-contrib/blob/master/plugin/instagram.rb)!

**Comment by kp1** [comment]
一応、
https://gist.github.com/kp1/d48d7a8b3b5358c532e3
でなおりました。

**Comment by tamoot** [comment]
プラグインが二つあるのは・・・どうしたらいいのかなぁと思いつつも、PRはマージしました。本issueは閉じますm(_ _)m
