### ISSUE TITLE
preview.rbでサーバーがハングする

### ISSUE THREAD

**Issue by kp1** [tdiary/tdiary-contrib#116]
起きた現象は、

* amazon.rbでproxyサーバーが落ちている状態
* amazon.rbのプラグイン呼び出しを含むものがプレビューされる
* サーバーごと応答できなくなる

です。

amazon.rbで対処するべきなのかもしれませんが、とりあえず上げておきます。

**Comment by tamoot** [comment]
(同じ現象に遭遇しました

**Comment by machu** [comment]
サーバーからエラーが返ってきたら自動プレビューをやめるようにしたほうがよさそうですね。

**Comment by machu** [comment]
安全側に倒して、プレビューに失敗した場合は自動プレビューを止めるようにしました。
26ad36ee2ae12d33721665abdfacec04b8502071

**Comment by kp1** [comment]
tDiaryのサーバーからプロキシサーバーへの経路を遮断して、
プレビューが停止すること、tDiaryのサーバが止まらないことを確認できました！
