### ISSUE TITLE
misc/tdiarygraphのswfファイルのソースが存在しない

### ISSUE THREAD

**Issue by henrich** [tdiary/tdiary-contrib#123]
特にライセンスが明記されていないのでGPL-2のはずですが、misc/tdiarygraphのswfファイルのソースが存在しません。

**Comment by hsbt** [comment]
過去の ML などを見てみましたがバイナリを持っている人から集めたというもののようなので non-free としてリポジトリを分離してライセンスは GPL 以外にするのが良いかなと思いました。

@tdtds ソースに心当たりありますか?

**Comment by tdtds** [comment]
このプラグインをいまだに利用してる人を見たことがないので、削除しちゃってもいいんじゃないかなぁ、さすがに。

**Comment by hsbt** [comment]
では、ライセンス不明のため削除ってことにしましょう〜

**Comment by hsbt** [comment]
@henrich misc/tdiarytimes も対象ですよね?
