### ISSUE TITLE
js/prettify 以下のJSファイルのminifiedされていないコードがない

### ISSUE THREAD

**Issue by henrich** [tdiary/tdiary-contrib#124]
js/prettify 以下のJSファイルがminifiedされています。
難読化に相当しますので元のコードが必要です。

**Comment by hsbt** [comment]
ご指摘ありがとうございます。

https://github.com/google/code-prettify

オリジナルを使用するか、オリジナルから minify するというように直そうと思います。

**Comment by henrich** [comment]
単純にminifyしてないものも同梱する形でもいいかと思います。

**Comment by hsbt** [comment]
今、同梱しているものが https://github.com/google/code-prettify と同一のものか確認したのちに、同梱の方針を考えようと思います!
