### ISSUE TITLE
picasa.rbで「Recently uploaded photos」が取れなくなっている

### ISSUE THREAD

**Issue by tdtds** [tdiary/tdiary-contrib#147]
まだコードを追ってないので、メモ程度ですが。

「Picasaから写真を取得する」ボタンを押したあとに出てくる「Recently uploaded photos」で写真の一覧が取れなくなっているようです。その後「Picasa Web Album」をクリックするとアルバムの一覧は出るので、利用に不都合はないですが。

**Comment by smallstyle** [comment]
Picasa側で何か変更があったのか，API呼び出し時に指定するパラメータでkind:photoを指定すると取得できなくなった(?)ようです．

https://developers.google.com/picasa-web/docs/2.0/reference#Kind

kindパラメータを外すと以前と同じデータは取得できるので，いったんkindパラメータを除去する方向で修正します．

**Comment by tdtds** [comment]
指定しなければデフォルトの`photo`が指定されたとみなされるわけですね。というかこれってAPIのバグなのでは……

修正、お任せします。来週29日にリリースがあるのでよろしくお願いします:smile:

**Comment by smallstyle** [comment]
その後，よくよく確認したところデフォルトは`photo`ではなくて`album`だったようです．いったん，利用できなくなった機能は削除し，アルバム一覧を最初から表示するように修正しました．

アナウンスではPicasa APIについて何らかの変更などがありそうな感じなので，また情報が更新されたら，改めて対応しようと思います．
