### ISSUE TITLE
socialbutton.rbではてなブックマークの挙動がおかしい

### ISSUE THREAD

**Issue by tdtds** [tdiary/tdiary-contrib#148]
tDiary 5.0.0でsocialbuttonプラグインを使ってはてなブックマークのボタンを貼ると、個々の日付のページでは正しくその日のブックマークへのリンクになるが、トップページなどでは(日付ページではなく)すべて日記トップへのブックマークになってしまう。

**Comment by machu** [comment]
同じ症状がでています。

socialbutton.jsでHTMLを生成するところまでは、個別ページのURLが埋め込まれています。

```html
<a href="https://b.hatena.ne.jp/entry/http://www.machu.jp/diary/20160117.html#p01"
 class="hatena-bookmark-button"
 data-hatena-bookmark-title="PlayStation4を買った"
 data-hatena-bookmark-layout="standard" 
 title="このエントリーをはてなブックマークに追加">
 <img src="https://b.st-hatena.com/images/entry-button/button-only.gif"
  alt="このエントリーをはてなブックマークに追加" width="20" height="20" style="border: none;">
</a>
<script type="text/javascript" src="https://b.st-hatena.com/js/bookmark_button.js" charset="utf-8" async="async"></script>
```

このあと、はてなのスクリプトでiframeに変換するときにURLが変わっているように見えます。うーん。

**Comment by tdtds** [comment]
日別ページでも「#p01」とかが消えてるようにみえる。いつもはここからブクマするとちゃんｔｐ「#p01」がついたページにされたのに、いまは違う。これははてブ側のバグないし仕様変更か?

**Comment by satoryu** [comment]
はてなのブックマークボタンの[ページ](http://b.hatena.ne.jp/guide/bbutton)を見ると、ボタンの見た目が変わってるんですが、仕様が変わったか何かがあったのではないでしょうか？

**Comment by tdtds** [comment]
#154 にて、いちおう直ったと思います。はてブのスクリプトを読んでみたら、href属性に加えて追加のdata属性を使っていたので、そちらも設定するようにしたら正しく参照されるようになりました。

なお、デザインの変更はsimple-baloonというスタイルが標準になっていただけでしたが、せっかくなのでそれも。
