### ISSUE TITLE
category_to_tagcloud.rbの不具合

### ISSUE THREAD

**Issue by ntee** [tdiary/tdiary-contrib#151]
使用環境
- tDiary 5.0.0
- Ruby 2.3.0
- category_to_tagcloud.rbとcategory-legacy.rbとの組み合わせ（category.rbは外しています）

1)「設定 - ヘッダ・フッタ」で<%=tag_list%>と書いても何も表示されません。
2) 日記を追記または更新すると以下のエラーが発生しました。ただし、その際に書いたものは正常に記録されています。

>
 Errors in plugins? Retry to Edit(2016-04-03) or Configure.
 NameError
 uninitialized constant #<Class:0x007fb72bf28048>::Category::Tagcloud_Info
 (plugin/category_to_tagcloud.rb):107:in `gen_tag_list'
 (plugin/category_to_tagcloud.rb):141:in `block (2 levels) in load_plugin'
 /app/lib/tdiary/plugin.rb:150:in `block in update_proc'
 /app/lib/tdiary/plugin.rb:149:in `each'
 /app/lib/tdiary/plugin.rb:149:in `update_proc'
 /app/lib/tdiary/admin.rb:122:in `block in do_eval_rhtml'
 /app/lib/tdiary/admin.rb:122:in `instance_eval'
 /app/lib/tdiary/admin.rb:122:in `do_eval_rhtml'
 /app/lib/tdiary/base.rb:30:in `eval_rhtml'
 /app/lib/tdiary/dispatcher/update_main.rb:22:in `run'
 /app/lib/tdiary/dispatcher/update_main.rb:6:in `run'
 /app/lib/tdiary/dispatcher.rb:26:in `dispatch_cgi'
 /app/lib/tdiary/dispatcher.rb:21:in `call'
 /app/lib/tdiary/rack/auth/omniauth/authorization.rb:26:in `call'
 /app/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
 /app/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
 /app/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/builder.rb:63:in `call'
 /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
 /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
 /app/lib/tdiary/rack/session.rb:14:in `call'
 /app/lib/tdiary/rack/auth/omniauth.rb:30:in `call'
 /app/lib/tdiary/rack/auth.rb:16:in `call'
 /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
 /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
 /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
 /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
 /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
 /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
 /app/lib/tdiary/application.rb:63:in `call'
 /app/vendor/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/configuration.rb:227:in `call'
 /app/vendor/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/server.rb:561:in `handle_request'
 /app/vendor/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/server.rb:406:in `process_client'
 /app/vendor/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/server.rb:271:in `block in run'
 /app/vendor/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/thread_pool.rb:111:in `block in spawn_thread'

**Comment by smallstyle** [comment]
カテゴリプラグインが有効か確認する処理の部分で，`category.rb`から`category-legacy.rb`が存在するかチェックするように修正しました．

**Comment by ntee** [comment]
最新版に更新して、両方とも解決しました。ありがとうございます。
