### ISSUE TITLE
preview プラグイン使用時の pre プラグインの挙動

### ISSUE THREAD

**Issue by yutopia** [tdiary/tdiary-contrib#161]
ロリポップ環境のため ruby-2.0.0 までしか使えないため、tDiary 4.2.1 を使用しています。
* plugin/preview.rb
* plugin/ja/preview.rb
* plugin/en/preview.rb
* js/preview.js

を入れて右にプレビューが表示されるようにして使用しているのですが、先程この状態で pre プラグインを使用したところプレビューが表示されなくなりました。
記述内容は
```
あああ<%= pre '
aaaa ' %>
````
のようにしています。
日記の登録そのものは問題なく、一度登録したあとで追記をしたらプレビューは正常にされていました。

**Comment by machu** [comment]
おそらく書きかけの日記をプレビューしようとして、エラーで自動プレビューが止まってしまったようです。エラーの時も自動プレビューを止めないようにします。

**Comment by yutopia** [comment]
とりあえず正常にプレビューされることを確認しました。

**Comment by yutopia** [comment]
ネタバレプラグインでも再現しました。
プレビューボタンを押しても表示はされません。
netabare_start と netabare_end の組をコピペした途端にプレビューが止まりました。
(ちなみに、 pre プラグインのときもプレビューボタンを押したときにプレビューはされていませんでした。

**Comment by machu** [comment]
ネタバレプラグインは使っていないのですが、show_and_hideプラグインで再現しました。いちどプラグインエラーになるとプレビューが表示されなくなりますね。

**Comment by machu** [comment]
プラグインエラーが起きてもプレビューが消えないよう、 #166 で修正しました。今度は大丈夫だと思います。

**Comment by yutopia** [comment]
大丈夫みたいです。
ありがとうございます。

**Comment by initialAK** [comment]
いったんクローズされた後にすみません。

netabare_start と netabare_end の組を一気に書く(ペーストする)のではなく、
netabare_start したあとまだ netabare_end してないタイミングで更新されると、
画面幅によらずプレビューが右ではなく上に表示され、更新フォームが増殖します。
先に netabare_end してから戻って netabare_start することで回避できますが、
文章の流れに逆行して書くのも何だかなぁ、と。

そこで実験的に自分の環境で $tDiary.plugin.preview.interval を 0 に設定すると
自動プレビュー機能を抑止して、手動でプレビューボタンを押すようにしてみました。
使い勝手の悪さと引き換えに、更新されても問題のないタイミングを見計らうという
選択肢が与えられます。高頻度で自動更新されたいひとも最短 1 秒なら許容範囲？

このような仕様変更を伴いますが、ネタバレに限らず start ～ end の組で使われる
プラグインが start したまま end せずにおかしな状態になるのを回避できるかと。
もしよろしければ採否をご検討ください。

**Comment by machu** [comment]
更新フォームが増えるのは変ですね。手元に環境がないので再現できませんが。
自動プレビューを止めるのであれば、更新間隔を大きな値（36000秒=10時間）にするのもありかと思いました。いいUIがあれば、編集画面で自動更新の有効・無効を切り替えたいんですけどね。

いずれにせよ、プルリク歓迎です！

**Comment by initialAK** [comment]
更新フォームが増えるのは start ～ end の組で書くプラグインを使って start だけ書いた状態なら、
手動でプレビューボタンを押しても再現するので、プレビューの自動化が直接の原因ではないです。
プレビューしちゃダメなタイミングでも時間が来たらプレビューされるから、たまたま当たっただけです。

なので、自動更新の有効・無効を切り替えたいという需要はあると思うのですが、
自分とこの実験バージョンみたく設定画面へ遷移して数値を変えなくても、
編集画面に居ながら切り替えができるほうがいいですね。

ちなみに、増殖した更新フォームは div.autopagerize_page_element 要素内にありました。
