### ISSUE TITLE
flickr.rb: 設定画面での標準の画像サイズと編集画面での写真選択ですべてのサイズを選べるようにしたい

### ISSUE THREAD

**Issue by senosa** [tdiary/tdiary-contrib#167]
flickr.photos.getSizesで取得できるサイズのうち、

* large square
* small 320
* medium 800
* original

が編集画面で選択できない。(medium 640 は設定画面での標準の画像サイズにも指定できない)

特に理由がないのであればすべてのサイズを選べるようにしたいと思うのですが（originalはさすがに不要かな？）どうでしょうか？

**Comment by machu** [comment]
新しく増えたサイズに対応できていないだけなので、ぜひ！640のほうはバグですね。とほほ。
http://www.slickrflickr.com/2613/new-flickr-photo-sizes/
