### ISSUE TITLE
profileプラグインでgravatarが動作しない

### ISSUE THREAD

**Issue by tdtds** [tdiary/tdiary-contrib#179]
原因追求してる時間がないので、とりあえずメモだけ。profile.rbの第二引数で`:gravatar`を指定するとエラーになります。APIがTimeoutしてるっぽいので、向こう側で何か変更があったのかも。

**Comment by machu** [comment]
いま試してみたら、gravatarにも普通につながりました。一時的に調子が悪かっただけかもです。

https://www.gravatar.com/a94c6a1e28e5618eb8e69039de9f5690.json

**Comment by tdtds** [comment]
APIが返ってきてるのはこちらでも確認。ただ、プラグインがエラーになるのは変わらず。あとでのんびり調べます……

**Comment by machu** [comment]
手元の環境 (ruby2.4.1 + mester) だと、ちゃんと動いているんですよねぇ。

```
<%= profile('kmachu@gmail.com', :gravatar) %>
```

キャッシュデータ (profile.pstore) を消しても変わりませんか？

**Comment by tdtds** [comment]
PRを作った #187
