### ISSUE TITLE
nicovideo.rb の https 対応

### ISSUE THREAD

**Issue by yutopia** [tdiary/tdiary-contrib#182]
ニコニコ動画の埋め込みフォームそのものが https に対応しておらず、現状では https な環境の tDiary で nicovideo.rb を使用すると動作不良となるようです。

公式の埋め込みフォームが https に対応するまで、とりあえず場つなぎの処置が必要です。

php版では以下のようなものがあるようです。
https://github.com/128na/NicoIframe

**Comment by tdtds** [comment]
なるほど、nicovideo_playerプラグインが吐き出すjavascriptがhttpなのが原因なんですね。
リンク先にあるようなhttpsに変換するproxyサーバをたてるのはあまりに大げさでメンテし続けるのも難しいので、たとえばhttpsからnicovideo_playerを呼び出した場合にはnicovideoプラグインにフォールバックするというのはどうでしょうね?

**Comment by yutopia** [comment]
ちょっと具体的なイメージがわかないのですが、サムネイルが表示されてとりあえず動画が再生できれば個人的にはとりあえず良いのではないかと思っています。
ちゃんと見たい人はニコニコ動画に直に飛んでもらえば良いのではないかと。
異論はあるかもしれませんが。

**Comment by tdtds** [comment]
はい、日記がhttpsの場合は、nicovideo_playerを使ってもnicovideoと同様のサムネイル付きリンクにしてしまおうというアイデアです。再生するためにはリンク先へ飛ばないといけませんが、まったく再生できないよりはマシなので、ニコ動がhttps化するまではこれでしのげばいいかな、と。

**Comment by tdtds** [comment]
#188にて修正しました。2017-06-29のリリースに入る予定です。

**Comment by yutopia** [comment]
ありがとうございます。確認しました。
