### ISSUE TITLE
instagram.rb : iframeをclass付きdivで囲んでほしい

### ISSUE THREAD

**Issue by kmuto** [tdiary/tdiary-contrib#215]
https://github.com/tdiary/tdiary-contrib/blob/4829dffbafccbd9561e5bbadc325b89a891399e0/plugin/instagram.rb#L22

で直にiframeを置いていますが、これだとCSSで調整しづらいため、たとえば`<div class="embed-instgram">`〜`</div>`みたいなもので囲むようにしていただけないでしょうか。

**Comment by tdtds** [comment]
賛成です。iframeを使うようなembed系のプラグインではほぼすべてに言える気もしますね。サービス固有のクラス名と、embed系共通のクラス名の両方が指定されていると便利そう。
