### ISSUE TITLE
tweet_quote.rb が動作しない

### ISSUE THREAD

**Issue by mfjt** [tdiary/tdiary-contrib#218]
Heroku で 5.1.1 にバージョンを上げてから動作しなくなりました。

```
wrong number of arguments (given 2, expected 1)

(plugin/tweet_quote.rb):44:in `escape'
(plugin/tweet_quote.rb):44:in `twitter_statuses_show_api'
(plugin/tweet_quote.rb):145:in `block in tweet_quote'
 :
```

https://github.com/tdiary/tdiary-contrib/blob/b12b62d305a7dcef85ff9d7dad84a8d18da7223c/plugin/tweet_quote.rb#L44

**Comment by satoryu** [comment]
コードを確認したところ、`URI.escape` から`CGI.escape` への移行の際に、この誤った変更が紛れていたようです。
- https://github.com/tdiary/tdiary-contrib/pull/214/files#diff-8fadb9c643fc32a3c565b58f7a359e33

`CGI.escape` は引数は1つのみなので、渡している`unsafe`を無くせば動きそうな気がします。

**Comment by hsbt** [comment]
修正の PR 作っときました。

@tdtds 見てくださいー

**Comment by tdtds** [comment]
わー、ごめんなさい、見落としてました！
